repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 297ff78
    hooks:
      - id: commitizen
        stages: [commit-msg]
  -   repo: https://github.com/thoughtworks/talisman
      rev: cdc8d06
      hooks:
      -   id: talisman-commit
          name: talisman
          language: system
          pass_filenames: false
          types: [text]
          verbose: true
