repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 7573d16
    hooks:
      - id: commitizen
        stages: [commit-msg]
  -   repo: https://github.com/thoughtworks/talisman
      rev: bf3f7b8
      hooks:
      -   id: talisman-commit
          name: talisman
