trigger:
 batch: true
 branches:
  include:
    - master
   
pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: UseDotNet@2
  displayName: 'Download .Net Core SDK'
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
    performMultiLevelLookup: true
- task: DotNetCoreCLI@2
  displayName: 'Dotnet Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'Quiet'
- task: DotNetCoreCLI@2
  displayName: 'DotNet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release --no-restore'
- task: DotNetCoreCLI@2
  displayName: 'DotNet Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory) --no-restore --no-build'
    zipAfterPublish: false
- task: PublishBuildArtifacts@1
  displayName: 'Upload Release'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'coredep'
